export const actionTypes = {
  GET_PRODUCTS: "GET_PRODUCTS",
  GET_PRODUCT_DETAIL: "GET_PRODUCT_DETAIL",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
};
